from edelweissfe.materials.marmotinterfacematerial.marmotinterfacematerialwrapper import test_MarmotInterfaceMaterialWrapper

def test_marmotinterfacematerialwrapper():
    test_MarmotInterfaceMaterialWrapper()
